# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3181abaceb56ae1eef73428e0869c7cc"
name = "bundle-20-discount"
application_url = "https://bundle-20-discount.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts"

[auth]
redirect_urls = [ "https://bundle-20-discount.vercel.app/api/auth" ]
